<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->

<html>
    <head>
        <base/>
        <link/>
    </head>
    <body>
        <area alt=""/>
        <br/>
        <table>
            <colgroup>
                <col/>
            </colgroup>
        </table>
        <embed/>
        <hr/>
        <img src="" alt=""/>
        <input type="text" id="test_input"/>
        <keygen/>
        <link/>
        <meta/>
        <param name="" value=""/>
        <video>
            <source/>
            <track src=""/>
        </video>
        <wbr/>

        <label for="test_input"/>
        <style type="text/css"/>
        <div/>
        <span/>
        <text/>
        <render/>
        <each/>
        <translate/>
        <scope/>
    </body>
</html>
