<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->

<html>
<head>
    <base/>
    <link/>
</head>
<body>
    <area alt=""/>
    <br/>
    <table>
        <colgroup>
            <col/>
        </colgroup>
    </table>
    <embed/>
    <hr/>
    <img src="" alt=""/>
    <input type="text" id="test_input"/>
    <link/>
    <meta/>
    <video>
        <source/>
        <track src=""/>
    </video>
    <wbr/>
    <hr/>
    <hr style="color: red" />
</body>
</html>
