<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->

<html>
    <head>
        <base/>
        <link/>
    </head>
    <body>
        <area alt=""/>
        <br/>
        <table>
            <colgroup>
                <col/>
            </colgroup>
        </table>
        <embed/>
        <hr/>
        <img src="" alt=""/>
        <input type="text" id="test_input"/>
        <input type="text"
               id="multi-line-input"
               placeholder="Alert should be on last line"
               />
        <input type="text"
               id="multi-line-input2"
               placeholder="Alert should be on last line" />
        <link/>
        <meta/>
        <video>
            <source/>
            <track src=""/>
        </video>
        <wbr/>

        <label for="test_input"/>
        <label
               for="multi-line-input"
               />
        <label
               for="multi-line-input2" />
        <style type="text/css"/>
        <div/>
        <span/>
        <text/>
        <render/>
        <each/>
        <translate/>
        <scope/>
        <span/>
        <span style="color: red" />
    </body>
</html>
