<?php

/**
 * Class ClassAnnotationFixture
 */
class ClassAnnotationFixture
{
    /**
     *
     * @inheritdoc
     */
    public function getProductListDefaultSortBy1()
    {
    }
}

/**
 * @SuppressWarnings(PHPMD.NumberOfChildren)
 */
class ClassAnnotationNoShortDescriptionFixture
{
}

/**
 * Class ClassAnnotationNoSpacingBetweenLinesFixture
 * @see Magento\Sniffs\Annotation\_files
 */
class ClassAnnotationNoSpacingBetweenLinesFixture
{

}
