<?php

/**
 * Nesting separator.
 */
define("NESTING_SEPARATOR", '->0');

/**  */
define('NUMBER_ONE', 1);

/**
 * @deprecated
 */
define('A', 65);

/**
 * @deprecated It is a lie
 */
define('THERE IS', 'cake');

/**
 * @deprecated
 * @see
 */
define('C', 67);

/**
 * @deprecated No reference specified
 * @see
 */
define('D', 68);

class Profiler
{
    /**
     * Nesting separator.
     */
    const NESTING_SEPARATOR = '->';

    /**
     *
     */
    const NUMBER_TWO = 2;

    /**
     * @deprecated
     */
    const a = 97;

    /**
     * @deprecated Why not
     */
    const YES = false;

    /**
     * @deprecated
     * @see
     */
    const c = 99;

    /**
     * @deprecated No reference specified
     * @see
     */
    const d = 100;

    /**
     * @deprecated This constant will be removed in version 1.0.0 without replacement
     */
    const KEYWORD_PHRASE = false;

    /**
     * @deprecated It's awesome - This constant will be removed in version 1.0.0 without replacement
     */
    const WITH_KEYWORD_PHRASE = false;
}
