<?php

/**
 * Directory separator shorthand, intended to make code more readable.
 */
define('DS', DIRECTORY_SEPARATOR);

define('BP', dirname(__FILE__));

/**
 * @deprecated New implementation available
 * @see \Ascii\Asterisk
 */
define('ANSWER', '42');

class Profiler
{
    const NESTING_SEPARATOR = '->';

    /**
     * Unlike first const, this one is not self explanatory.
     */
    const NUMBER_TWO = 2;

    /**
     * @deprecated Unable to identify the question, replaced
     * @see \ComputationalMatrix\Earth
     */
    const COMPUTER = 'Deep Thought';

    /**
     * @deprecated
     * @see \ComputationalMatrix\Mars
     */
    const KEYBOARD = 'Ergonomic';

    /**
     * @see
     */
    const SOMETHING = 'else';
}
