<?php

/**
 * Nesting separator.
 */
define("NESTING_SEPARATOR", '->0');

/**  */
define('NUMBER_ONE', 1);

/**
 * @deprecated
 */
define('A', 65);

/**
 * @deprecated Slightly better, but no see tag
 */
define('B', 66);

/**
 * @deprecated
 * @see
 */
define('C', 67);

/**
 * @deprecated No reference specified
 * @see
 */
define('D', 68);

class Profiler
{
    /**
     * Nesting separator.
     */
    const NESTING_SEPARATOR = '->';

    /**
     *
     */
    const NUMBER_TWO = 2;

    /**
     * @deprecated
     */
    const a = 97;

    /**
     * @deprecated Slightly better, but no see tag
     */
    const b = 98;

    /**
     * @deprecated
     * @see
     */
    const c = 99;

    /**
     * @deprecated No reference specified
     * @see
     */
    const d = 100;
}
