<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/x-magento-init">
</script>
<script type="text/javascript">
</script>
<div id="block-testing"
     class="block shipping"
     data-mage-init='{}'
>
<?php
function _testing()
{
    return true;
}
$_productCollection = $block->_getTestFunction();
$block->getTestFunction();
$_something = $this->something();
$block->_getTest();
$block = _testing();
?>
<?php
$block->_getTestAnotherFunction();
?>

<?php $scriptString = <<<script
    require([
        "jquery",
        "jquery/ui",
    ], function ($, Confirm) {
    });
script;
$this->helper();
?>
<script type="jquery/ui">
</script>

<p>This sniff should remove the any <code> type="text/javascript" </code> attributes from &lt;script&gt; tags, but not from elsewhere in the document.</p>

<script type='text/javascript'></script>
<script type="TEXT/JAVASCRIPT"></script>
<SCRIPT TYPE="text/javascript"></SCRIPT>
<script>
    const type="text/javascript";
</script>
