<?php

if (count($array) > 0) {
    //
}

if ((anotherFunc($array) !== 0) && count($array) > 0) {
    //
}

if ((count($array) !== 0) && (((anotherFunc($array))))) {
    //
}

if (((count($array)))) {
    //
}

if (count($array) && (anotherFunc($array) !== 0)) {
    //
}

if ($findme === 'a' && (count($array) || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (count($array) != 0 || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (count($array) > 10 || $findme !== 'b') && $mystring !== false) {
    //
}

if (($column->getId() === 'store_id' || count($array) > 0 || $column->getId() === 'status') && $column->getFilter()->getValue()) {
    //
}

$length = count($array);

if ('count' != $foo && count($bar)) {
    //
}

if ($findme === 'a' and (count($array) != 0 or $findme !== 'b') and $mystring !== false) {
    //
}

if (strlen($string) > 0) {
    //
}

if ((anotherFunc($string) !== 0) && strlen($string) > 0) {
    //
}

if ((strlen($string) !== 0) && (((anotherFunc($string))))) {
    //
}

if (((strlen($string)))) {
    //
}

if (strlen($string) && (anotherFunc($string) !== 0)) {
    //
}

if ($findme === 'a' && (strlen($string) || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (strlen($string) != 0 || $findme !== 'b') && $mystring !== false) {
    //
}

if ($findme === 'a' && (strlen($string) > 10 || $findme !== 'b') && $mystring !== false) {
    //
}

if (($column->getId() === 'store_id' || strlen($string) > 0 || $column->getId() === 'status') && $column->getFilter()->getValue()) {
    //
}

if (strlen($string . implode(',', $array)) && (anotherFunc($string) !== 0)) {
    //
}

if (strlen($string . implode(',', $array)) > 10 && (anotherFunc($string) !== 0)) {
    //
}

$length = strlen($string);

if ($findme === 'a' and (strlen($string) > 0 or $findme !== 'b') and $mystring !== false) {
    //
}

if (strlen($string) < $limit) {
    //
}

if (strlen($string) >= getLimit()) {
    //
}
